const router = require('express').Router();
const categoryController = require('../controllers/category.controller');
const auth = require('../middlewares/auth');
router.get('/', categoryController.all);
router.get('/:key', categoryController.get);
router.post('/', auth, categoryController.create);
router.put('/:key', auth, categoryController.update);
router.delete('/:key', auth, categoryController.delete);
router.patch('/:key', auth, categoryController.restore);
module.exports = router;
